import commonjs from "@rollup/plugin-commonjs";
import { nodeResolve } from "@rollup/plugin-node-resolve";
import typescript from "@rollup/plugin-typescript";

/**
 * @type {import('rollup').RollupOptions[]}
 */
const config = [
  {
    input: "src/index.ts",
    output: [
      {
        file: "dist/json-selector.umd.js",
        format: "umd",
        name: "jsonSelector",
        sourcemap: true,
      },
    ],
    plugins: [
      // needed to include the parser generated by peggy
      commonjs(),
      // include dependencies in bundle
      nodeResolve(),
      typescript({ tsconfig: "tsconfig.build.json" }),
    ],
  },
  {
    input: "src/index.ts",
    external: ["fast-deep-equal", "moo"],
    output: [
      {
        file: "dist/json-selector.esm.js",
        format: "esm",
        sourcemap: true,
      },
    ],
    plugins: [
      // needed to include the parser generated by peggy
      commonjs(),
      typescript({ tsconfig: "tsconfig.build.json" }),
    ],
  },
];

export default config;
